name = "tec-ec-election"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

# Serve static assets for the frontend
[assets]
directory = "public"
binding = "ASSETS"

# Durable Object for rate limiting
[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

[[migrations]]
tag = "v1"
new_classes = ["RateLimiter"]

# KV Namespace for OTPs and sessions
[[kv_namespaces]]
binding = "KV"
id = "9ab7e56be47340f4a4e7aac22091a268"

# D1 Database for persistent data
[[d1_databases]]
binding = "DB"
database_name = "tec-ec-election-db"
database_id = "eaff7896-8279-4f7d-8551-1647d03c7102"

[vars]
# Environment variables
# ADMIN_EMAIL = "admin@example.com"
# RESEND_FROM_EMAIL = "voting@election.tecouncil.org"
# RESEND_API_KEY = "..." (set via wrangler secret put RESEND_API_KEY)
